"""
Extrai cookies do navegador do usuário para usar no yt-dlp e pytubefix.
Permite downloads autenticados usando a sessão do YouTube do navegador.
"""

import browser_cookie3
import tempfile
import os
from typing import Optional
from pathlib import Path


class BrowserCookieExtractor:
    """Extrai cookies de navegadores para uso em downloads do YouTube"""
    
    def __init__(self):
        self.cookie_file = None
    
    def extract_youtube_cookies(self, domain: str = '.youtube.com') -> Optional[str]:
        """
        Extrai cookies do YouTube dos navegadores instalados.
        Retorna caminho para arquivo de cookies temporário no formato Netscape.
        
        Tenta extrair de (em ordem):
        1. Chrome/Chromium
        2. Firefox
        3. Edge
        4. Opera
        5. Brave
        
        NOTA: Em produção (Linux), cookies não estarão disponíveis.
        Esta funcionalidade é principalmente para desenvolvimento local.
        """
        try:
            print("🍪 Tentando extrair cookies do navegador...")
            
            # Lista de funções de extração de cookies por navegador
            extractors = [
                ('Chrome', browser_cookie3.chrome),
                ('Firefox', browser_cookie3.firefox),
                ('Edge', browser_cookie3.edge),
                ('Opera', browser_cookie3.opera),
                ('Brave', browser_cookie3.brave),
            ]
            
            cookies = None
            browser_used = None
            
            # Tenta cada navegador até conseguir
            for browser_name, extractor_func in extractors:
                try:
                    cookies = extractor_func(domain_name=domain)
                    if cookies:
                        browser_used = browser_name
                        print(f"  ✓ Cookies extraídos do {browser_name}!")
                        break
                except Exception:
                    # Silenciosamente ignora navegadores que falharem
                    continue
            
            if not cookies:
                print("  ℹ️ Cookies do navegador não disponíveis (normal em produção)")
                return None
            
            # Cria arquivo temporário de cookies no formato Netscape
            # (formato que yt-dlp e pytubefix aceitam)
            cookie_file = tempfile.NamedTemporaryFile(
                mode='w',
                suffix='.txt',
                delete=False,
                encoding='utf-8'
            )
            
            # Escreve cabeçalho do formato Netscape
            cookie_file.write("# Netscape HTTP Cookie File\n")
            cookie_file.write("# This file was generated by browser_cookie3\n")
            cookie_file.write("# Edit at your own risk.\n\n")
            
            # Converte cookies para formato Netscape
            cookie_count = 0
            for cookie in cookies:
                if hasattr(cookie, 'domain') and hasattr(cookie, 'name'):
                    # Formato Netscape:
                    # domain  flag  path  secure  expiration  name  value
                    domain = cookie.domain
                    flag = 'TRUE' if domain.startswith('.') else 'FALSE'
                    path = cookie.path if hasattr(cookie, 'path') else '/'
                    secure = 'TRUE' if (hasattr(cookie, 'secure') and cookie.secure) else 'FALSE'
                    expiration = str(int(cookie.expires)) if hasattr(cookie, 'expires') and cookie.expires else '0'
                    name = cookie.name
                    value = cookie.value if hasattr(cookie, 'value') else ''
                    
                    cookie_file.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n")
                    cookie_count += 1
            
            cookie_file.close()
            self.cookie_file = cookie_file.name
            
            print(f"✅ {cookie_count} cookies salvos em: {self.cookie_file}")
            return self.cookie_file
            
        except Exception as e:
            print(f"❌ Erro ao extrair cookies: {e}")
            return None
    
    def cleanup(self):
        """Remove arquivo temporário de cookies"""
        if self.cookie_file and os.path.exists(self.cookie_file):
            try:
                os.remove(self.cookie_file)
                print("🧹 Arquivo de cookies temporário removido")
            except Exception as e:
                print(f"⚠️ Erro ao remover cookies: {e}")
    
    def __del__(self):
        """Limpa cookies ao destruir objeto"""
        self.cleanup()


def get_youtube_cookies_file() -> Optional[str]:
    """
    Função helper para obter arquivo de cookies do YouTube.
    Retorna caminho do arquivo ou None se falhar.
    """
    extractor = BrowserCookieExtractor()
    return extractor.extract_youtube_cookies()
